custom:
  api:
    version: 32
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - refresh
          - hystrix.stream
info:
  application:
    name: Registration
    description: Microservice that perform registration of customers.
